# Install necessary packages if you haven't already
# install.packages(c("httr", "jsonlite", "stringr")) # Run manually if needed

library(httr)
library(jsonlite)
library(stringr)

# --- Configuration ---
GITHUB_ORG <- "Brian-Elbel-s-Research-Projects"
README_OUTPUT_FILE <- "README2.md" # The file to be updated

# Get GitHub Personal Access Token from environment variable (set by GitHub Actions)
GITHUB_TOKEN <- Sys.getenv("GITHUB_TOKEN")

if (nchar(GITHUB_TOKEN) == 0) {
  stop("Error: GITHUB_TOKEN environment variable not set.
       This script is intended to be run by GitHub Actions where GITHUB_TOKEN is automatically provided.")
}

# --- Function to get all repositories from GitHub API ---
get_all_org_repos <- function(org, token) {
  repos <- character()
  page <- 1
  
  while (TRUE) {
    url <- paste0("[https://api.github.com/orgs/](https://api.github.com/orgs/)", org, "/repos")
    headers <- add_headers(Authorization = paste0("token ", token),
                           Accept = "application/vnd.github.v3+json")
    params <- list(type = "all", per_page = 100, page = page)
    
    response <- GET(url, headers, query = params)
    
    # Check for HTTP errors
    stop_for_status(response) 
    
    page_repos <- fromJSON(content(response, "text", encoding = "UTF-8"))
    
    if (length(page_repos) == 0) {
      break # No more repositories
    }
    
    # Extract html_url for each repository
    repos <- c(repos, page_repos$html_url)
    page <- page + 1
  }
  return(sort(unique(repos))) # Return sorted unique URLs
}

# --- Main execution ---
if (!interactive()) { # Only run if not in an interactive R session (i.e., when run by Action)
  
  cat(paste0("Fetching repositories for organization: ", GITHUB_ORG, "...\n"))
  github_repos_urls <- get_all_org_repos(GITHUB_ORG, GITHUB_TOKEN)
  cat(paste0("Found ", length(github_repos_urls), " repositories on GitHub.\n"))
  
  # --- Generate Markdown content for the new section ---
  repo_list_markdown <- ""
  for (repo_url in github_repos_urls) {
    repo_name <- basename(repo_url) # Extracts "repo-name" from "[https://github.com/org/repo-name](https://github.com/org/repo-name)"
    repo_list_markdown <- paste0(repo_list_markdown, "* [", repo_name, "](", repo_url, ")\n")
  }
  
  new_section_markdown <- paste0(
    "\n\n",
    "## Index of All Repositories\n\n",
    "This section is automatically generated by a GitHub Action. It provides an up-to-date list of all public and private repositories under the `", GITHUB_ORG, "` organization. This automation helps ensure that this README always reflects the full scope of our projects on GitHub.\n\n",
    "\n",
    repo_list_markdown,
    "\n"
  )
  
  # --- Update README2.md ---
  readme_content <- character()
  if (file.exists(README_OUTPUT_FILE)) {
    readme_content <- readLines(README_OUTPUT_FILE, warn = FALSE)
  }
  
  start_marker <- ""
  end_marker <- ""
  
  start_line <- which(str_detect(readme_content, start_marker))
  end_line <- which(str_detect(readme_content, end_marker))
  
  if (length(start_line) > 0 && length(end_line) > 0 && start_line < end_line) {
    # If markers exist, replace content between them
    updated_content <- c(
      readme_content[1:(start_line - 1)],
      new_section_markdown,
      readme_content[(end_line + 1):length(readme_content)]
    )
  } else {
    # If markers don't exist, append the new section
    updated_content <- c(readme_content, new_section_markdown)
  }
  
  # Write the updated content back to the file
  writeLines(updated_content, README_OUTPUT_FILE, sep = "\n")
  cat(paste0("Successfully updated ", README_OUTPUT_FILE, " with the repository index.\n"))
}
