# Install necessary packages if you haven't already
# install.packages(c("httr", "jsonlite", "stringr")) # Run manually if needed

library(httr)
library(jsonlite)
library(stringr)

# --- Configuration ---
GITHUB_ORG <- "Brian-Elbel-s-Research-Projects"
README_OUTPUT_FILE <- "README2.md" # The file to be updated

# Get GitHub Personal Access Token from environment variable (set by GitHub Actions)
GITHUB_TOKEN <- Sys.getenv("GITHUB_TOKEN")

if (nchar(GITHUB_TOKEN) == 0) {
  stop("Error: GITHUB_TOKEN environment variable not set.
       This script is intended to be run by GitHub Actions where GITHUB_TOKEN is automatically provided.")
}

# --- Function to get all repositories from GitHub API ---
get_all_org_repos <- function(org, token) {
  repos <- character()
  page <- 1
  
  while (TRUE) {
    url <- paste0("https://api.github.com/orgs/", org, "/repos")
    headers <- add_headers(Authorization = paste0("token ", token),
                           Accept = "application/vnd.github.v3+json")
    params <- list(type = "all", per_page = 100, page = page)
    
    response <- GET(url, headers, query = params)
    
    # Check for HTTP errors
    stop_for_status(response) 
    
    page_repos <- fromJSON(content(response, "text", encoding = "UTF-8"))
    
    if (length(page_repos) == 0) {
      break # No more repositories
    }
    
    # Extract html_url for each repository
    repos <- c(repos, page_repos$html_url)
    page <- page + 1
  }
  return(sort(unique(repos))) # Return sorted unique URLs
}

# --- Main execution ---
if (!interactive()) { # Only run if not in an interactive R session (i.e., when run by Action)
  
  cat(paste0("Fetching repositories for organization: ", GITHUB_ORG, "...\n"))
  github_repos_urls <- get_all_org_repos(GITHUB_ORG, GITHUB_TOKEN)
  cat(paste0("Found ", length(github_repos_urls), " repositories on GitHub.\n"))
  
  # --- Generate Markdown content for the repository list (only what goes between markers) ---
  repo_list_markdown <- ""
  for (repo_url in github_repos_urls) {
    repo_name <- basename(repo_url) # Extracts "repo-name" from "https://github.com/org/repo-name"
    repo_list_markdown <- paste0(repo_list_markdown, "* [", repo_name, "](", repo_url, ")\n")
  }
  
  # IMPORTANT: These markers MUST match exactly between your R script and your README2.md file.
  start_marker <- ""
  end_marker <- ""
  
  # --- Read and Update README2.md ---
  readme_content <- character()
  if (file.exists(README_OUTPUT_FILE)) {
    readme_content <- readLines(README_OUTPUT_FILE, warn = FALSE)
  }
  
  start_line_num <- which(str_detect(readme_content, fixed(start_marker)))
  end_line_num <- which(str_detect(readme_content, fixed(end_marker)))
  
  if (length(start_line_num) > 0 && length(end_line_num) > 0 && start_line_num < end_line_num) {
    # If markers exist and are in correct order, replace content *between* them
    updated_content <- c(
      readme_content[1:start_line_num], # Include the start marker
      repo_list_markdown,                # Insert the generated list
      readme_content[end_line_num:length(readme_content)] # Include the end marker and content after it
    )
    cat("Markers found. Updating content between markers.\n")
  } else {
    # If markers don't exist or are malformed, append the new section (including header/explanation)
    new_section_header <- "## Index of All Repositories\n\n"
    new_section_explanation <- paste0(
      "This section is automatically generated by a GitHub Action. It provides an up-to-date list of all public and private repositories under the `", GITHUB_ORG, "` organization. This automation helps ensure that this README always reflects the full scope of our projects on GitHub.\n\n"
    )
    
    updated_content <- c(
      readme_content,
      "\n---\n", # Add a separator if appending a new section
      new_section_header,
      new_section_explanation,
      start_marker,
      "\n", # New line after start marker for readability
      repo_list_markdown,
      end_marker,
      "\n" # New line after end marker
    )
    cat("Markers not found or malformed. Appending new section to the end of the file.\n")
  }
  
  # Write the updated content back to the file
  writeLines(updated_content, README_OUTPUT_FILE, sep = "\n")
  cat(paste0("Successfully updated ", README_OUTPUT_FILE, " with the repository index.\n"))
}
