name: Update Repository Index Pushed

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

permissions:
  contents: write # Grants permission to write to the repository for committing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # GitHub's automatically provided token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # Specify the R version you want to use

      - name: Install R system dependencies for curl # <-- ADD THIS NEW STEP
        run: sudo apt-get update -qq && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          install.packages(c("httr", "jsonlite", "stringr"))
        shell: Rscript {0}

      - name: Run R script to update README2.md
        run: |
          # Keep these debug lines for now, or remove them if you're confident
          echo "--- Debugging File Paths ---"
          echo "Current working directory:"
          pwd
          echo "Files in current directory (root of your repo):"
          ls -F
          echo "Recursive file listing from root:"
          ls -R
          echo "--- Attempting to run R script ---"
          Rscript generate_repo_index.R
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_REPO_PAT }}

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Automated: Update repository index in README2.md'
          add: 'README2.md' # Only commit README2.md if it was updated
          # This action will only commit if there are changes
